/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InseratNeuRouteImport } from './routes/inserat-neu'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as ProjektHilfeRouteImport } from './routes/projekt-hilfe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InseratNeuRoute = InseratNeuRouteImport.update({
  id: '/inserat-neu',
  path: '/inserat-neu',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektHilfeRoute = ProjektHilfeRouteImport.update({
  id: '/projekt-hilfe',
  path: '/projekt-hilfe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inserat-neu': typeof InseratNeuRoute
  '/inspiration': typeof InspirationRoute
  '/projekt-hilfe': typeof ProjektHilfeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inserat-neu': typeof InseratNeuRoute
  '/inspiration': typeof InspirationRoute
  '/projekt-hilfe': typeof ProjektHilfeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inserat-neu': typeof InseratNeuRoute
  '/inspiration': typeof InspirationRoute
  '/projekt-hilfe': typeof ProjektHilfeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/inserat-neu' | '/inspiration' | '/projekt-hilfe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/inserat-neu' | '/inspiration' | '/projekt-hilfe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/inserat-neu'
    | '/inspiration'
    | '/projekt-hilfe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InseratNeuRoute: typeof InseratNeuRoute
  InspirationRoute: typeof InspirationRoute
  ProjektHilfeRoute: typeof ProjektHilfeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inserat-neu': {
      id: '/inserat-neu'
      path: '/inserat-neu'
      fullPath: '/inserat-neu'
      preLoaderRoute: typeof InseratNeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt-hilfe': {
      id: '/projekt-hilfe'
      path: '/projekt-hilfe'
      fullPath: '/projekt-hilfe'
      preLoaderRoute: typeof ProjektHilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InseratNeuRoute: InseratNeuRoute,
  InspirationRoute: InspirationRoute,
  ProjektHilfeRoute: ProjektHilfeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
